# -*- coding: utf-8 -*-
"""Another copy of prkunutulan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7A4Do3dHsXFIZmyeLKlJJPh95P0y0wn
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from google.colab import files
uploaded = files.upload()

data = pd.read_csv('/content/wdbc2.data', header=None)

# Load dataset
data = pd.read_csv('/content/wdbc2.data', header=None)

# Set initial column names, including the ID column
data.columns = [
    "ID", "Diagnosis", "radius1", "texture1", "perimeter1", "area1", "smoothness1",
    "compactness1", "concavity1", "concave_points1", "symmetry1", "fractal_dimension1",
    "radius2", "texture2", "perimeter2", "area2", "smoothness2", "compactness2",
    "concavity2", "concave_points2", "symmetry2", "fractal_dimension2",
    "radius3", "texture3", "perimeter3", "area3", "smoothness3", "compactness3",
    "concavity3", "concave_points3", "symmetry3", "fractal_dimension3"
]

# Drop the ID column
data = data.drop(columns="ID")

# Replace Diagnosis values if necessary (e.g., 'M' for malignant, 'B' for benign)
data['Diagnosis'] = data['Diagnosis'].map({'M': 'malignant', 'B': 'benign'})

# Separate features and labels
X = data.drop(columns='Diagnosis')
y = data['Diagnosis']

data

# Menghapus data duplikat, menyimpan data dalam variabel baru "dataClean"
dataClean = data.drop_duplicates()
print("All Duplicate Rows:")
dataClean[dataClean.duplicated(keep=False)]

# 1. Split data menjadi 60% training dan 40% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=43)

# 2. Latih model Gaussian Naive Bayes pada data training dan hitung akurasi
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# Prediksi pada data training dan testing
y_train_pred = gnb.predict(X_train)
y_test_pred = gnb.predict(X_test)

# Hitung akurasi model awal pada data training dan testing
train_accuracy_gnb = accuracy_score(y_train, y_train_pred)
test_accuracy_gnb = accuracy_score(y_test, y_test_pred)

print("Hasil Model Gaussian Naive Bayes (sebelum tuning):")
print("Akurasi pada data training:", train_accuracy_gnb)
print("Akurasi pada data testing:", test_accuracy_gnb)

# 3. Lakukan oversampling sebagian untuk menyeimbangkan data training
ros = RandomOverSampler(sampling_strategy=0.8, random_state=42)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

# 4. Hyperparameter tuning dengan RandomizedSearchCV pada Gaussian Naive Bayes
param_grid = {'var_smoothing': np.logspace(-9, -3, 7)}
random_search = RandomizedSearchCV(estimator=GaussianNB(), param_distributions=param_grid, n_iter=10, scoring='accuracy', cv=5, random_state=42)
random_search.fit(X_resampled, y_resampled)

# Dapatkan model terbaik dari RandomizedSearchCV
best_gnb = random_search.best_estimator_

# Prediksi dengan model terbaik pada data training dan testing
y_train_pred_best = best_gnb.predict(X_train)
y_test_pred_best = best_gnb.predict(X_test)

# Hitung akurasi model terbaik pada data training dan testing
train_accuracy_best = accuracy_score(y_train, y_train_pred_best)
test_accuracy_best = accuracy_score(y_test, y_test_pred_best)

print("\nHasil Model Gaussian Naive Bayes (setelah tuning dengan RandomizedSearchCV):")
print("Akurasi pada data training:", train_accuracy_best)
print("Akurasi pada data testing:", test_accuracy_best)